### ISSUE TITLE
Looks like a PMS Update broke the plugin.

### ISSUE THREAD

**Issue by harroguk** [meriko/FilmOn.bundle#3]
Last Working on...
1.4.4.3495-edef59192

Broken in...
1.5.0.3501-3b8374a5c
Still broken in...
1.5.1.3520-ed60c70d6

**Comment by meriko** [comment]
Working for me with 1.5.1.3520 with iOS for example.

Which client are you using? If the new PMS force the client to transcode it won't work since PMS can't transcode HLS livestreams(used by Filmon) into a new HLS livestream. However PMS can transcode a HLS livestream into a MKV livestream, so for some clients that prefer MKV when transcoding it still might work(I remember that, for example, it worked on Chromecast some time ago which prefers MKV)

Unfortunately nothing can be done in this channel to affect the handshake between client<->PMS, i.e. whether to direct play or transcode. It simple hands over the URL to the video stream...

**Comment by harroguk** [comment]
Clients in use are...
Webclient
XBoxOne
PS4

**Comment by meriko** [comment]
I just tested on PS4 and it worked/direct played. What are your video settings?

My settings:
All qualities(local, remote, online): "Original"
Allow Direct Play boxed
Allow Direct Stream boxed
Max H.264 level: 4.1

I also tested Plex/Web(Chrome) and it transcoded it ok? Same settings as above(except for the H.264 which doesn't exist in Plex/Web)

**Comment by harroguk** [comment]
Set the settings the same as yours, installed the latest PMS, rebooted the server after installation and now the channel is working fine again.

No clue why it wasnt playing but as it is now I am happy again. :)
